<div id="contents" class="judgstep03 text03m">
    <div class="judgstep03contents">
        <h2>該非判定書発行依頼</h2>
        <ul>
            <li><img src="/resources/image/judg_step01off_02off.gif" width="238" height="33" alt="依頼内容の入力">
            </li>
            <li><img src="/resources/image/judg_step02off_03on.gif" width="238" height="33" alt="入力内容の確認">
            </li>
            <li><img src="/resources/image/judg_step03on.gif" width="238" height="33" alt="判定書作成">
            </li>
        </ul>
            <div class="outlines">
                <p>該非判定書発行依頼を承りました。</p>
                <p class="pb10">ご依頼内容をメールにてお送りしておりますのでご確認ください。</p>
            </div>
        <div class="companyadress">
            <?php echo Zynas_Registry::getConfig()->constants->contact_disco?>
        </div>
    </div>
</div>
