<title><?php echo $this->pageTitle = 'インフォメーション詳細 ｜ 該非判定WEBシステム ｜ 株式会社ディスコ'; // ページタイトル ?>
</title>
<?php $this->isNotHeader = true; ?>
<div id="header">
	<h1>
		<a href="http://www.disco.co.jp"><img src="/resources/image/logo.jpg"
			alt="DISCO" width="205" height="48" border="0"> </a>
	</h1>
</div>

<div id="gnavi02"></div>

<div id="contents" class="infodetail text03m">
	<div class="infodetailcontents">
		<h2>インフォメーション詳細</h2>
		<div class="infodetailtable">
			<table border="0" cellpadding="0" cellspacing="0"
				style="text-align: left;">
				<tbody>
					<tr>
						<th class="infodetailtablebb">タイトル</th>
						<td class="infodetailtablebb"><?php echo $this->infDetail->title; ?>
						</td>
					</tr>
					<tr>
						<th class="infodetailtablebb">作成年月日</th>
						<td class="infodetailtablebb"><?php echo $this->dateFormat($this->infDetail->create_date,'Y/m/d'); ?>
						</td>
					</tr>
					<tr>
						<th style="width: 182px !important">詳細情報</th>
						<td><?php echo nl2br($this->infDetail->detail); ?></td>
					</tr>
				</tbody>
			</table>
			<ul>
				<li class="cancell"><a href="#"
					onClick="window.close(); return false;">閉じる</a></li>
			</ul>
		</div>
	</div>
</div>
