<title><?php echo $this->pageTitle = 'パスワード確認 ｜ 該非判定WEBシステム ｜ 株式会社ディスコ'; // ページタイトル ?>
</title>
<?php $this->isNotHeader = true; ?>

<div id="header">
	<h1>
		<a href="http://www.disco.co.jp"><img src="/resources/image/logo.jpg"
			alt="DISCO" width="205" height="48" border="0"> </a>
	</h1>
</div>

<div id="gnavi02"></div>

<div id="contents" class="pwcheck morefooterspace text03m">
	<p class="outline">
		登録したE-mailアドレスを入力し、送信ボタンを押してください。<br> E-mailアドレス宛にパスワードをお送りいたします。
	</p>
	<div style="color: red;">
	<?php echo $this->dumpFlashMessages(); ?>
	</div>
	<form action="/recover/confirm-request" method="post">
		<div class="inputbox">
			<ul>
				<li class="inputtxt">E-mailアドレス</li>
				<li><?php echo $this->formText('mailAddress', $this->escape($this->request->mailAddress), array('maxlength' => '255', 'size' => '30', 'class' => 'w300'));?>
					<br>
					<div style="color: red; text-align: left;">
					<?php echo $this->formError('mailAddress'); ?>
					</div>
				</li>
			</ul>
		</div>
		<div class="pwcheckbtns">
			<ul>
				<li><?php echo $this->formButtonTo(null, '戻る', '/auth/login', array('class' => 'zbtn_back')); ?>
				</li>
				<li><?php echo $this->formSubmit(null, '送信', array('class' => 'zbtn_short', 'style' => 'margin-left: 12px;')); ?>
				</li>
			</ul>
		</div>
	</form>
</div>

