<div id="contents" class="judgstep03 text03m">
    <div class="judgstep03contents">
        <h2>該非判定書発行依頼</h2>
        <ul>
            <li><img src="/resources/image/judg_step01off_02off.gif" width="238" height="33" alt="依頼内容の入力">
            </li>
            <li><img src="/resources/image/judg_step02off_03on.gif" width="238" height="33" alt="入力内容の確認">
            </li>
            <li><img src="/resources/image/judg_step03on.gif" width="238" height="33" alt="判定書作成">
            </li>
        </ul>
        <div class="outlines">
            <p>
                該非判定書発行依頼を承りました。
            </p>
            <p class="pb10">
                お客様のご依頼内容をメールにてお送りしておりますのでご確認ください。
            </p>
            <p class="pb10">
                ご依頼頂きました該非判定書は、本日より３営業日以内に当社営業又は
                <br>
                輸出管理担当者より提出いたします。
                <br>
                （発行までにお時間がかかる場合は、その旨３営業日以内にご連絡差し上げます。）
            </p>
            <p>
                確認メールが届いていない又は３営業日を過ぎても連絡がない場合は、
                <br>
                お手数ですが当社品質保証部までお問い合わせください。
            </p>
        </div>
        <div class="companyadress">
            <?php echo Zynas_Registry::getConfig()->constants->contact?>
        </div>
    </div>
</div>
