<title><?php echo $this->pageTitle = 'Day la trang dung de test';?></title>
<div style="color: red;">
	<?php echo $this->dumpFlashMessages(); ?>
	</div>
<div id="contents" class="infoud text03m">
	<div class="infoudcontents">
		<h2>Edit User</h2>
		<div class="infoudtable">
			<form action="/testing/edit" method="post" id="submitForm"
				name="submitForm">
				<table>
					<tbody>
						<tr>
							<th class="infoudtablebb">Username</th>
							<td class="infoudtablebb">
							<?php echo $this->formText('username', $this->request-> username, array('class' => 'w300'));?>
							<div style="color: red; text-align: left;">
								<?php echo $this->formError('username'); ?>
								</div>
							</td>
						</tr>
						<tr>
							<th class="infoudtablebb">Password</th>
							<td class="infoudtablebb">
							<?php echo $this->formPassword('password', $this->request-> password, array('class' => 'w300'));?>
							</td>
						</tr>
						<tr>
							<th class="infoudtablebb">Full Name</th>
							<td class="infoudtablebb">
							<?php echo $this->formText('fullname', $this->request-> fullname, array('class' => 'w300'));?>
							</td>
						</tr>
						<tr>
							<th class="infoudtablebb">Position</th>
							<td class="infoudtablebb">
							<?php $select = $this->formSelect ( 'position', $this->request->position, array (
									'label' => 'Position'), $this->lstoption );
								echo $select;
							?>
							</td>
						</tr>
						</tbody>
				</table>
				<table class="ztable_horizontal">
					<tr>
					<td><?php echo $this->formButtonTo('btnBack', 'Cancel', '/testing/', array('class' => 'zbtn_back')); ?></td>
						<td><?php echo $this->formButton('btSave', 'Save', array('class' => 'zbtn_short')); ?>
						</td>
					</tr>
				</table>
				<!-- Lay ra dia chi id tren url -->
				<?php echo $this->formHidden('id', $this->request->id); ?>
				<!-- Day la token -->
				<?php echo $this->formHidden('token', $this->token); ?>
				<?php echo $this->formHidden('addressid', $this->request->t_addressid); ?>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
$("#btSave").click(function(){
	$("#submitForm").submit();
});

$(function(){
	$("#position").val($("#addressid").val());
});
</script>