<title><?php echo $this->pageTitle = 'メンテナンス中 ｜ 該非判定WEBシステム ｜ 株式会社ディスコ'; // ページタイトル ?>
</title>
<?php $this->isNotHeader = true; ?>
<div id="header">
	<h1>
		<a href="http://www.disco.co.jp"><img src="/resources/image/logo.jpg"
			alt="DISCO" width="205" height="48" border="0"> </a>
	</h1>
</div>

<div id="gnavi02"></div>
<h2 class="pb10"><img src="/resources/image/service_ttl.gif" width="716" height="46" alt="該非判定書発行サービス"></h2>
<div id="contents" class="morefooterspace text03m">
		<div class="maintenance">
			<p><img src="/resources/image/icon_maintenance.gif" width="64" height="62" alt=""></p>
			<div class="maintetext">
				<h3>システムメンテナンス中です。</h3>
				<p>現在、システムメンテナンスを行っております。<br>
				該非判定書発行サービスをご利用のみなさまには大変ご迷惑をおかけしまして<br>
				誠に申し訳ございません。<br>
				もうしばらくお待ちください。</p>
			</div>
			<div class="companyadress">
				<p>株式会社ディスコ<br>
				品質保証部・輸出管理担当</p>
				<p>TEL：03-4590-1064</p>
			</div>
		</div>
	</div>
