<title><?php echo $this->pageTitle='FAQ登録・更新 ｜ 該非判定WEBシステム ｜ 株式会社ディスコ'?>
</title>
<script type="text/JavaScript">
$(function(){
    $("#information tbody tr:even").addClass("even");
    $("#information tbody tr:odd").addClass("odd");
});
</script>

<div id="contents" class="faqud text03m">
	<div class="faqudcontents">
		<h2>FAQ登録・更新</h2>
		<p class="outline">
			<span class="faqabsolute">必須</span>のついている項目は必ずご入力ください
		</p>
		<div class="faqudtable">
			<form id="submitForm" action="/admin-faq/confirm-edit" method="post">
				<table border="0" cellpadding="0" cellspacing="0">
					<tbody>
						<tr>
							<th class="faqudtablebb">タイトル<span class="faqabsolute">必須</span>
							</th>
							<td class="faqudtablebb"><?php echo $this->formText('title', $this->request->title, array('class' => 'w300', 'style' => 'margin-left: -40px;'));?>(全角半角●文字以内入力)
								<br>
								<div style="color: red; text-align: left;">
								<?php echo $this->formError('title'); ?>
								</div>
							</td>
						</tr>
						<tr>
							<th class="faqudtablebb" valign="top">質問<span class="faqabsolute">必須</span>
							</th>
							<td class="faqudtabletextarea faqudtablebb"
								style="text-align: left"><?php echo $this->formTextarea('question', $this->request->question, array('size' => '5','class' => 'w300'));?>(全角・半角入力)
								<br>
								<div style="color: red;">
								<?php echo $this->formError('question'); ?>
								</div>
							</td>
						</tr>
						<tr>
							<th class="faqudtablebb" valign="top"
								style="border-bottom: none;">回答<span class="faqabsolute">必須</span>
							</th>
							<td class="faqudtabletextarea" style="text-align: left"><?php echo $this->formTextarea('answer', $this->request->answer, array('size' => '5','class' => 'w300'));?>
								<br>
								<div style="color: red;">
								<?php echo $this->formError('answer'); ?>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
				<br>
				<?php echo $this->formHidden('token', $this->token);?>
				<?php echo $this->formHidden('id', $this->request->id); ?>
				<table class="ztable_horizontal">
					<tr>
						<td><?php echo $this->formButtonTo(null, '戻る', '/admin-faq/list', array('class' => 'zbtn_back')); ?>
						</td>
						<td><?php echo $this->formButton(null, '変更', array('class' => 'zbtn_short','onclick'=> 'onConfirmEdit();')); ?>
						</td>
					</tr>
				</table>
			</form>
		</div>
	</div>
</div>

        <!-- yes/no dialog -->
        <div class="modal" id="yesno" title="確認">
            <p>編集します。よろしいですか？</p>
        </div>


<script type="text/javascript">
	function onClickPreview() {
		document.getElementById('submitForm').action ='/admin-faq/preview';
		document.getElementById('submitForm').target ='_blank';
		document.getElementById('submitForm').submit();
	}

	function onClickSubmit(){
		document.getElementById('submitForm').action ='/admin-faq/confirm-edit';
		document.getElementById('submitForm').target ='_self';
		document.getElementById('submitForm').submit();
	}

    function onConfirmEdit() {
        $("#yesno" ).dialog({
         resizable: false,
         height:140,
         modal: true,
         buttons: {
             "はい": function() {
                var submitForm = document.getElementById('submitForm');
                submitForm.action ='/admin-faq/confirm-edit';
                submitForm.target ='_self';
               $("#submitForm").submit();
             },
             "キャンセル": function() {
                 $( this ).dialog( "close" );
             }
         }
     });
    }
    	
</script>
