<title><?php echo $this->pageTitle = '発行依頼 ｜ 該非判定WEBシステム ｜ 株式会社ディスコ'; //?>
</title>
<div id="contents" class="judgstep03_2 text03m">
	<div class="judgstep03_2contents ml20">
		<h2>該非判定書発行依頼</h2>
		<ul>
			<li><img src="/resources/image/judg_step01off_02off.gif" width="238"
				height="33" alt="依頼内容の入力"></li>
			<li><img src="/resources/image/judg_step02off_03on.gif" width="238"
				height="33" alt="入力内容の確認"></li>
			<li><img src="/resources/image/judg_step03on.gif" width="238"
				height="33" alt="判定書作成"></li>
		</ul>
		<div class="outlines">
			<p>
				該非判定書が出来上がりました。<br> 以下のボタンを右クリックし「対象をファイルに保存」で保存して下さい。
			</p>
			<p>
				<a href=<?php ?>>該非判定書を開く</a>
			</p>
			<p>尚作成した判定書は、「発行履歴」よりご確認頂けます。</p>
			<p>
				また、ご依頼頂いた原紙の方は、ご依頼内容をメールにてお送りしておりますので<br> ご確認ください。
			</p>
			<p>
				お依頼頂きました該非判定書は、本日より３営業日以内に当社営業又は<br> 輸出管理担当者より提出いたします。<br>
				(発行までにお時間がかかる場合は、その旨３営業日以内にご連絡差し上げます。)
			</p>
			<p>
				確認メールが届いていない 又は ３営業日を過ぎても連絡がない場合は、<br> お手数ですが当社品質保証部までお問い合わせください。
			</p>
		</div>
		<div class="companyadress">
			<p>
				株式会社ディスコ<br> 品質保証部・輸出管理担当
			</p>
			<p>TEL：03-4590-1064</p>
		</div>
	</div>
</div>
